# Generated by Django 4.1.8 on 2023-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='estate_planning_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='investment_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='life_insurance_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='long_term_care_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='medicare_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='retirement_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='savings_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tax_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='videos',
        ),
    ]
