# Generated by Django 4.2.1 on 2023-07-20 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_estate_planning_video_investment_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate_planning_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='estate_planning_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='investment_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='investment_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='life_insurance_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='life_insurance_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='long_term_care_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='long_term_care_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='medicare_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='medicare_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='retirement_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='retirement_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='savings_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='savings_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AddField(
            model_name='tax_video',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='tax_video',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
        migrations.AlterField(
            model_name='estate_planning_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='investment_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='life_insurance_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='long_term_care_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicare_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='retirement_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savings_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tax_video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
