# Generated by Django 4.1.8 on 2023-07-22 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_estate_planning_video_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_video',
            fields=[
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
                ('title', models.CharField(default='Title', max_length=500)),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
