# Generated by Django 4.2.1 on 2023-08-08 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_other_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_video',
            fields=[
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
                ('title', models.CharField(default='Title', max_length=500)),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
