# Generated by Django 4.1.8 on 2023-08-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_exam_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='savings_video',
            new_name='college_university_savings_video',
        ),
    ]
