# Generated by Django 4.2.1 on 2023-08-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_savings_video_college_university_savings_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college_university_savings_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='estate_planning_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='exam_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='investment_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='life_insurance_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='long_term_care_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='medicare_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='other_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='retirement_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='tax_video',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='college_university_savings_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estate_planning_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='life_insurance_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='long_term_care_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicare_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='other_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retirement_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tax_video',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
