# Generated by Django 4.2.1 on 2023-08-27 23:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_college_university_savings_video_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Structure_Video',
            fields=[
                ('my_order', models.PositiveIntegerField(default=0)),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
                ('title', models.CharField(default='Title', max_length=500)),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='General_Financial_Planning_Video',
            fields=[
                ('my_order', models.PositiveIntegerField(default=0)),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
                ('title', models.CharField(default='Title', max_length=500)),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Real_Estate_Investment_Video',
            fields=[
                ('my_order', models.PositiveIntegerField(default=0)),
                ('link', models.CharField(max_length=1000)),
                ('password', models.CharField(default='N/A', max_length=40)),
                ('title', models.CharField(default='Title', max_length=500)),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.RenameModel(
            old_name='investment_video',
            new_name='asset_protection_video',
        ),
    ]
