# Generated by Django 4.2.1 on 2023-07-17 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 20, 16, 25, 445876)),
            preserve_default=False,
        ),
    ]
