# Generated by Django 4.2.1 on 2023-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/files/pictures/default.jpg', upload_to='blogs/files/pictures'),
        ),
    ]
