# Generated by Django 4.2.5 on 2024-03-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/pictures/default.jpg', null=True, upload_to='blog/pictures/'),
        ),
    ]
