# Generated by Django 4.2 on 2023-04-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='start',
        ),
    ]
