# Generated by Django 4.2 on 2023-04-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_password_users_end_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='meetings',
        ),
    ]
