# Generated by Django 4.1.8 on 2023-04-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_users_meetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifed_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
