# Generated by Django 4.1.8 on 2023-05-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_message_recepients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='recepients',
        ),
    ]
