# Generated by Django 4.1.8 on 2023-05-08 22:53

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_message_delete_recepients'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifed_user',
            name='videos',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
