# Generated by Django 4.2.1 on 2023-05-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_message_delete_recepients'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifed_user',
            name='video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
