# Generated by Django 4.1.8 on 2023-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_verifed_user_video_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifed_user',
            old_name='video_number',
            new_name='estate_planning_video_number',
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='investment_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='life_insurance_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='long_term_care_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='medicare_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='retirement_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='savings_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifed_user',
            name='tax_video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
