# Generated by Django 4.1.8 on 2023-05-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_verifed_user_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifed_user',
            name='videos',
        ),
    ]
