# Generated by Django 4.1.8 on 2023-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_video_verifed_user_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid_type',
            field=models.CharField(choices=[('tax', 'Taxes'), ('saving', 'College/University Savings'), ('retirement', 'Retirement Plans'), ('life_insurance', 'Life Insurance'), ('investment', 'Investment'), ('estate_planning', 'Estate Planning'), ('long_term_care', 'Long Term Care'), ('medicare', 'Medicare')], default='Taxes', max_length=100),
        ),
    ]
