# Generated by Django 4.1.8 on 2023-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_delete_meetings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifed_user',
            name='other_video_number',
            field=models.IntegerField(default=1),
        ),
    ]
