# Generated by Django 4.2.1 on 2023-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_webinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='link',
            field=models.TextField(default='https://www.youtube.com'),
        ),
    ]
