# Generated by Django 4.2.1 on 2023-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_webinar_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_qrcode', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
    ]
