# Generated by Django 4.2.1 on 2023-08-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_agent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_contact',
            name='wechat_qrcode',
            field=models.ImageField(blank=True, default='contact/pictures/default.jpg', null=True, upload_to='contact/pictures/'),
        ),
    ]
