# Generated by Django 4.2.1 on 2023-08-08 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_agent_contact_wechat_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
