# Generated by Django 4.2.1 on 2023-08-19 21:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_webinar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='english_webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('link', models.TextField(default='https://www.youtube.com')),
            ],
        ),
        migrations.CreateModel(
            name='inner_webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('link', models.TextField(default='https://www.youtube.com')),
            ],
        ),
        migrations.RenameModel(
            old_name='webinar',
            new_name='chinese_webinar',
        ),
    ]
