# Generated by Django 4.1.8 on 2023-08-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_english_webinar_inner_webinar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inner_webinar',
            name='link',
        ),
    ]
