# Generated by Django 4.2.1 on 2023-08-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_everyones_video_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EVERYONES_VIDEO_NUMBER',
            new_name='everyone_video_number',
        ),
    ]
